/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as VercelRouteRouteImport } from './routes/vercel/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VercelIndexRouteImport } from './routes/vercel/index'
import { Route as StripeIndexRouteImport } from './routes/stripe/index'
import { Route as VercelPricingRouteImport } from './routes/vercel/pricing'
import { Route as VercelDocsRouteImport } from './routes/vercel/docs'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelRouteRoute = VercelRouteRouteImport.update({
  id: '/vercel',
  path: '/vercel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelIndexRoute = VercelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VercelRouteRoute,
} as any)
const StripeIndexRoute = StripeIndexRouteImport.update({
  id: '/stripe/',
  path: '/stripe/',
  getParentRoute: () => rootRouteImport,
} as any)
const VercelPricingRoute = VercelPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => VercelRouteRoute,
} as any)
const VercelDocsRoute = VercelDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => VercelRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vercel': typeof VercelRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/vercel/docs': typeof VercelDocsRoute
  '/vercel/pricing': typeof VercelPricingRoute
  '/stripe/': typeof StripeIndexRoute
  '/vercel/': typeof VercelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vercel/docs': typeof VercelDocsRoute
  '/vercel/pricing': typeof VercelPricingRoute
  '/stripe': typeof StripeIndexRoute
  '/vercel': typeof VercelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vercel': typeof VercelRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/vercel/docs': typeof VercelDocsRoute
  '/vercel/pricing': typeof VercelPricingRoute
  '/stripe/': typeof StripeIndexRoute
  '/vercel/': typeof VercelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vercel'
    | '/about'
    | '/vercel/docs'
    | '/vercel/pricing'
    | '/stripe/'
    | '/vercel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/vercel/docs'
    | '/vercel/pricing'
    | '/stripe'
    | '/vercel'
  id:
    | '__root__'
    | '/'
    | '/vercel'
    | '/about'
    | '/vercel/docs'
    | '/vercel/pricing'
    | '/stripe/'
    | '/vercel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VercelRouteRoute: typeof VercelRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  StripeIndexRoute: typeof StripeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel': {
      id: '/vercel'
      path: '/vercel'
      fullPath: '/vercel'
      preLoaderRoute: typeof VercelRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel/': {
      id: '/vercel/'
      path: '/'
      fullPath: '/vercel/'
      preLoaderRoute: typeof VercelIndexRouteImport
      parentRoute: typeof VercelRouteRoute
    }
    '/stripe/': {
      id: '/stripe/'
      path: '/stripe'
      fullPath: '/stripe/'
      preLoaderRoute: typeof StripeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vercel/pricing': {
      id: '/vercel/pricing'
      path: '/pricing'
      fullPath: '/vercel/pricing'
      preLoaderRoute: typeof VercelPricingRouteImport
      parentRoute: typeof VercelRouteRoute
    }
    '/vercel/docs': {
      id: '/vercel/docs'
      path: '/docs'
      fullPath: '/vercel/docs'
      preLoaderRoute: typeof VercelDocsRouteImport
      parentRoute: typeof VercelRouteRoute
    }
  }
}

interface VercelRouteRouteChildren {
  VercelDocsRoute: typeof VercelDocsRoute
  VercelPricingRoute: typeof VercelPricingRoute
  VercelIndexRoute: typeof VercelIndexRoute
}

const VercelRouteRouteChildren: VercelRouteRouteChildren = {
  VercelDocsRoute: VercelDocsRoute,
  VercelPricingRoute: VercelPricingRoute,
  VercelIndexRoute: VercelIndexRoute,
}

const VercelRouteRouteWithChildren = VercelRouteRoute._addFileChildren(
  VercelRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VercelRouteRoute: VercelRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  StripeIndexRoute: StripeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
